config/routes.rb
Rails.application.routes.draw do
  resources :scrapers
  root to: "listings#home"
	resources :listings, :phrases
	
	post '/listings_filter', to: 'listings#filter'
	get '/listings_filter', to: 'listings#filter'
	
	post '/listings_search', to: 'listings#search'
	get '/listings_search', to: 'listings#search'
	
  get '/discriminatory', to: 'listings#discriminatory'
  get '/visualization', to: 'listings#visualization'
  post '/tools/stats', to: 'stats#get_stats'
  get '/tools/stats', to: 'stats#index'
  get '/tools/trackchanges', to: 'trackchanges#index'
  post '/tools/trackchanges', to: 'trackchanges#get_changes'
  get '/tools/trackform', to: 'trackchanges#trackform'
  get '/Contact', to: 'contacts#index'
end

app/models/listing.rb
class Listing < ApplicationRecord
	has_many :phrase_listings
  has_many :phrases, through: :phrase_listings

  before_save :check_discriminatory_and_set_flag
  after_save :add_phrase_listing_entries

  def illegal?
    return self.discriminatory
  end

	def self.get_filtered_listings(phrase)
		@filtered_listings = []
		Listing.all.each do |listing|
			if listing.check_phrase(phrase)
				@filtered_listings.push(listing)
			end
		end
		puts '------------------------------------------------------------------'
		puts "#{@filtered_listings.count} listings counted for phrase: #{phrase}"
		puts '------------------------------------------------------------------'
		@filtered_listings
	end

  def check_phrase(phrase)
    regex = phrase.strip.gsub(' ','\s+')
    reg_obj = Regexp.new(/#{regex}/i)
    if reg_obj.match(self.description)
      true
    else
      false
    end
  end

	def self.set_discriminatory
		Listing.all.each do |listing|
			listing.illegal?
		end
	end

  def self.discriminatory
    Listing.all.select {|listing| listing.discriminatory == true}
  end

	def self.num_listings
		Listing.all.count
	end

	def self.num_discriminatory
		Listing.discriminatory.count
	end

# default values for dates, if none are passed in
# format for date arguments: 'yyyy-mm-dd', or any portion of a date starting with 'yyyy'
  def self.date_range(start_date_str='2000-2-1', end_date_str='')
    start_date = Date.parse(start_date_str)
    end_date = Date.parse(end_date_str)
		@listings_in_range = []
		Listing.all.each do |phrase_listing|
			listed = phrase_listing.listed_at
			if listed
				if listed >= start_date && listed <= end_date
					@listings_in_range.push(phrase_listing)
				end
			end
		end
		@listings_in_range
	end

  private

  # Returns an array of discriminory phrases found in the listing
  def find_discriminatory_phrases
    found_phrases = []
    Phrase.all.each do |phrase|
      if self.check_phrase(phrase.content)
        found_phrases.append(phrase)
      end
    end
    return found_phrases
  end

  def check_discriminatory_and_set_flag
    found_phrases = find_discriminatory_phrases
    if found_phrases.empty?
      self.discriminatory = false
    else
      self.discriminatory = true
    end
  end

  def add_phrase_listing_entries
    if self.discriminatory
      found_phrases = find_discriminatory_phrases
      for phrase in found_phrases do
        PhraseListing.create(listing_id: self.id, phrase_id: phrase.id)
      end
    end
  end
end

app/controllers/listings_controller.rb
require 'pry'

class ListingsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
		@listings = Listing.paginate(:page => params[:page], :per_page => 50)
		@phrases = Phrase.all
		@phrase = 'temp'
    respond_to do |format|
      format.html
      format.json {render json: @listings.to_json}
    end
  end

  def show
    set_listing
    render_listing_formats
  end

  def edit
    set_listing
    render_listing_formats
  end

  def update
    set_listing
    set_listing.update(listing_params)
    render_listing_formats
  end

  def visualization
      puts "show"
    @listings = Listing.all
    render_listings_formats
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.save
    render_listing_formats
  end

  def discriminatory
		@listings = Listing.discriminatory
		@phrases = Phrase.all
		@phrase = 'temp'
    render_listings_formats
  end
	
	def filter
		@phrase =  Phrase.find_by_id(params[:temp][:phrase_id].to_i).content
		@listings = Listing.get_filtered_listings(@phrase)
		render :template => "listings/filtered"
	end
	
	def search
		@phrase = params[:temp][:phrase]
		@listings = Listing.get_filtered_listings(@phrase)
		render :template => "listings/filtered"
	end
	
  def home
  end

  private
	def listing_params
    params.require(:listing).permit(:id, :address, :listed_at, :latitude, :longitude, :description, :discriminatory, :heading)
  end

  def set_listing
    @listing = Listing.find_by(id: params[:id])
  end

  def render_listing_formats
    respond_to do |format|
      format.html
      format.json {render json: @listing.to_json}
    end
  end

  def render_listings_formats
    respond_to do |format|
      format.html {render :template => "listings/index"}
      format.json {render json: @listings.to_json}
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_filter.html.erb
<%= form_for @phrase, url: {action: "filter"} do |f| %>
	<%= f.collection_select(:phrase_id, phrases, :id, :content) %>
	<%= f.submit value='Filter' %>
<% end %>

app/views/listings/_search.html.erb
<%= form_for @phrase, url: {action: "search"} do |f| %>
	<%= f.text_field :phrase %>
	<%= f.submit value='Search' %>
<% end %> 
 

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/filtered.html.erb
<div class="container">
  <div class="row">
		<div class="col-sm-12">
			<h3 class='results'>Returned listings count: <%= @listings.count %>, for phrase: <%= @phrase %></h3>
  		<hr />
			<table class="table" data-toggle="table" >
        <thead>
          <tr>
            <th data-sortable="true" class="heading-label">id</th>
            <th data-sortable="true" class="heading-label">heading</th>
            <th data-sortable="true" class="date-time-label">listed at</th>
            <th data-sortable="true" class="address-label">address</th>
            <th data-sortable="true" class="latitude-label">latitude</th>
            <th data-sortable="true" class="longitude-label">longitude</th>
            <th data-sortable="true" class="description-label">description</th>
            <th data-sortable="true" class="descriminatory-label">discriminatory</th>
          </tr>
        </thead>
        <tbody>
          <% @listings.each do |listing| %>
            <tr class="housing-column">
              <td class="heading-item"><%= listing.id %></td>
              <td class="heading-item"><%= link_to listing.heading, listing_path(listing) %></td>
              <td class="date-time-item"><%= listing.listed_at %></td>
              <td class="address-item"><%= listing.address %></td>
              <td class="latitude-item"><%= listing.latitude %></td>
              <td class="longitude-item"><%= listing.longitude %></td>
              <td class="description-item"><%= listing.description %></td>
              <td class="descriminatory-item"><%= listing.discriminatory %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="panel-footer">
        <div class="row">
          <div class="col col-xs-offset-3 col-xs-6">
            <nav aria-label="Page navigation" class="text-center">
              <ul class="pagination">
                <li>
                  <a href="#" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                  </a>
                </li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li>
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">»</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
		</div>
  </div>
</div>

app/views/listings/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1 class="text-center">Understanding Discriminatory Housing in Boston</h1>
    </div>
    <div class="col-sm-4" id="housing-icon"></div>
    <div class="col-sm-4 image" id="housing-icon">

      <!-- Image on homepage, housing.svg -->
      <svg class="img-responsive" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
      	 viewBox="0 0 90 65" style="enable-background:new 0 0 90 65;" xml:space="preserve">
      <style type="text/css">
      	.st0{fill:#00F2DF;}
      </style>
      <g>
      	<path class="st0" d="M24.2,14H2.6C0.9,14,0,14,0,15.7V65h27V15.7C27,14,25.9,14,24.2,14z M8,52H3v-5h5V52z M8,43H3v-5h5V43z M8,33
      		H3v-5h5V33z M16,52h-5v-5h5V52z M16,43h-5v-5h5V43z M16,23h-5v-5h5V23z M24,43h-5v-5h5V43z M24,33h-5v-5h5V33z M24,23h-5v-5h5V23z"
      		/>
      	<path class="st0" d="M57.7,0H33.2C31.5,0,30,0.5,30,2.2V65h31V2.2C61,0.5,59.4,0,57.7,0z M39,48h-3v-7h3V48z M39,24h-3v-7h3V24z
      		 M39,14h-3V6h3V14z M47,48h-3v-7h3V48z M47,36h-3v-8h3V36z M47,14h-3V6h3V14z M55,48h-3v-7h3V48z M55,36h-3v-8h3V36z M55,24h-3v-7
      		h3V24z M55,14h-3V6h3V14z"/>
      	<path class="st0" d="M86.9,36H67.4c-1.7,0-3.4,0.1-3.4,1.7V65h26V37.7C90,36.1,88.5,36,86.9,36z M72,50h-5v-4h5V50z M72,44h-5v-4h5
      		V44z M80,50h-6v-4h6V50z M87,50h-5v-4h5V50z M80,56h-6v-4h6V56z M87,56h-5v-4h5V56z M80,44h-6v-4h6V44z"/>
      </g>
      </svg>

    </div>
    <div class="col-sm-4" id="housing-icon"></div>
    <div class="col-sm-12">
      <p class="text-center">This is a project for the City of Boston that addresses the potential discriminatory housing rental practices in Boston as manifested through Craigslist postings.</p>
    </div>
  </div>
</div>

app/views/listings/index.html.erb
<div class="container">
  <div class="row">
		<div class="col-sm-2">
			<form class="form-horizontal" id="phrase">
				<%= collection_select(:phrase, :content, Phrase.all, :content, :content,{}, {class:'form-control'}) %>
				<button onclick="getDataByPhrase()" class="btn btn-default">Search selected phrase</button>
			</form>
		</div>
  </form>
</div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table" data-toggle="table" >
        <thead>
          <tr>
            <th data-sortable="true" class="heading-label">heading</th>
            <th data-sortable="true" class="date-time-label">listed at</th>
            <th data-sortable="true" class="address-label">address</th>
            <th data-sortable="true" class="latitude-label">latitude</th>
            <th data-sortable="true" class="longitude-label">longitude</th>
            <th data-sortable="true" class="description-label">description</th>
            <th data-sortable="true" class="descriminatory-label">discriminatory</th>
          </tr>
        </thead>
        <tbody>
          <% @listings.each do |listing| %>
            <tr class="housing-column">
              <td class="heading-item"><%= link_to listing.heading, listing_path(listing) %></td>
              <td class="date-time-item"><%= listing.listed_at %></td>
              <td class="address-item"><%= listing.address %></td>
              <td class="latitude-item"><%= listing.latitude %></td>
              <td class="longitude-item"><%= listing.longitude %></td>
              <td class="description-item"><%= listing.description %></td>
              <td class="descriminatory-item"><%= listing.discriminatory %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div class="panel-footer">
        <div class="row">
          <div class="col col-xs-offset-3 col-xs-6">
            <nav aria-label="Page navigation" class="text-center">
              <ul class="pagination">
                <li>
                  <a href="#" aria-label="Previous">
                    <span aria-hidden="true">«</span>
                  </a>
                </li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li>
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">»</span>
                  </a>
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
		</div>
		
  </div>
</div>

app/views/listings/show.html.erb
<div class="page-title">Discriminatory Listings</div>
<h3>Single listing </h3>
<div class="container">
		<% if @listing.discriminatory %>
			<h3> this listing is DISCRIMINATORY! </h3>
		<% end %>
		<p>id: <%= @listing.id %></p>
		<p>listed_at: <%= @listing.listed_at %></p>
		<p>address: <%= @listing.address %></p>
		<p>latitude: <%= @listing.latitude %></p>
		<p>longitude: <%= @listing.longitude %></p>
		<p>heading: <%= @listing.heading%></p>
		<p>description: <%= @listing.description %></p>
		<p>discriminatory: <%= @listing.discriminatory %></p>
</div>

app/views/listings/track_changes.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  <title>Legal Housing | Boston</title>
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet" type="text/css">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/skeleton.css">


  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="images/favicon.png">
</head>
<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
    <div class="row">
      <div class="twelve column" style="margin-top: 25%">
        <h1 style ="text-align:center;">Understanding Discriminatory Housing in Boston</h1>
        <div id = "housing-icon">
          <img src="assets/housing.svg">
        </div>
        <p>This is a project for the City of Boston that addresses the potential discriminatory housing rental practices in Boston as manifested through Craigslist postings.</p>
      </div>
    </div>
  </div>
  <div class="container">
    <button id="click-button">Button</button>
    <%= button_to "Run Scraper", scrapers_path %>

    <div class="filters">
      <%= form_for @listings, :url => {action: "track_changes"} do |f| %>
        <%= options_for_select([["1", "1"], ["2", "2"], ["3", "3"]]) %>
        <br>
        start date: <%= select_date Date.today, prefix: :start_date %>
        <br>
        end date: <%= select_date Date.today, prefix: :start_date %>
        <br>
        phrase: 
        <br>
        <%= submit_tag("Filter") %>
      <% end %>
    </div>

    <table>
      <tr id="headers">
        <th class="heading-label">heading</th>
        <th class="date-time-label">listed at</th>
        <th class="address-label">address</th>
        <th class="latitude-label">latitude</th>
        <th class="longitude-label">longitude</th>
        <th class="description-label">description</th>
        <th class="descriminatory-label">discriminatory</th>
      </tr>

      <% @listings.each do |listing| %>
        <tr class="housing-column">
          <td class="heading-item"><%= link_to listing.heading, listing_path(listing) %></td>
          <td class="date-time-item"><%= listing.listed_at %></td>
          <td class="address-item"><%= listing.address %></td>
          <td class="latitude-item"><%= listing.latitude %></td>
          <td class="longitude-item"><%= listing.longitude %></td>
          <td class="description-item"><%= listing.description %></td>
          <td class="descriminatory-item"><%= listing.discriminatory %></td>
        </tr>
      <% end %>
    </table>
  <%# will_paginate @listings %>

  </div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>