config/routes.rb
Rails.application.routes.draw do
  resources :scrapers
  root to: "listings#home"
	resources :listings, :phrases
	
	post '/listings_filter', to: 'listings#filter'
	get '/listings_filter', to: 'listings#filter'
	
	post '/listings_search', to: 'listings#search'
	get '/listings_search', to: 'listings#search'
	
  get '/discriminatory', to: 'listings#discriminatory'
  get '/visualization', to: 'listings#visualization'
  post '/tools/stats', to: 'stats#get_stats'
  get '/tools/stats', to: 'stats#index'
  get '/tools/trackchanges', to: 'trackchanges#index'
  post '/tools/trackchanges', to: 'trackchanges#get_changes'
  get '/tools/trackform', to: 'trackchanges#trackform'
  get '/Contact', to: 'contacts#index'
end

app/views/layouts/_header.html.erb
 
<div>
<%= link_to "Listings", listings_path %>
|
<%= link_to "Discriminatory", discriminatory_path %>
|
<%= link_to "Phrases", phrases_path %>
|
<%= link_to "Issues", issues_path %><br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HousingDataServer</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.14/css/highcharts.css" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <header class="navbar navbar-inverse navbar-fixed-top">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav">
        <li ><%= link_to "Home", root_path %></li>
				<li ><%= link_to "All Listings", listings_path %></li>
				<li ><%= link_to "Discriminatory", discriminatory_path %></li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Tools
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="/tools/stats">Stats</a></li>
            <li><a href="/tools/trackchanges">Listings Changes</a></li>
          </ul>
        </li>
        <!--<li><a href="/Contact">Contact</a></li>-->

      </ul>
    </div>
  </header>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/5.0.14/highcharts.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>
<%= yield %>
</body>
</html>